### ISSUE TITLE
Raising an Error when creating a proxy model for a computed fields model

### ISSUE THREAD

**Issue by M-Saeb** [netzkolchose/django-computedfields#107]
When I created a proxy model for model that inherits from `ComputedFieldsModel`, I get the following error:
```
Traceback (most recent call last):
  File ".\manage.py", line 22, in <module>
    main()
  File ".\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line       
    utility.execute()
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\computedfields\apps.py", line 27, in ready
    BOOT_RESOLVER.initialize()
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\computedfields\resolver.py", line 225, in initialize
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\computedfields\resolver.py", line 262, in load_maps
    self._graph, maps = self._graph_reduction()
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\computedfields\resolver.py", line 273, in _graph_reduction
    graph = ComputedModelsGraph(self.computed_models)
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\computedfields\graph.py", line 400, in __init__
    self.resolved = self.resolve_dependencies(computed_models)
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\computedfields\graph.py", line 452, in resolve_dependencies
    remove_segments = parent_to_inherited_path(real_field.model, model)
  File "F:\Programming\Intergrated Path\Seat Score\seatscore-backend\venv\lib\site-packages\computedfields\helper.py", line 40, in parent_to_inherited_path
    relations.append(model._meta.parents[base].remote_field.name)
AttributeError: 'NoneType' object has no attribute 'remote_field'
```

**Comment by jerch** [comment]
Eww, this looks like a regression to me (imho it used to work in the past).

**Comment by M-Saeb** [comment]
@jerch I posted a solution for it in this pull request #108

**Comment by jerch** [comment]
@M-Saeb Thx for looking into it - well, the patch does not yet pass all tests. Imho the proxy models need to filtered earlier in the bootrapping phase of the resolver. This would omit them completely for the graph reduction. A different take would postpone them, until the source model's deps got laid out, and add them as alias.

Currently I am not sure, if there are more issues around them - first there are no explicit tests (so the regression slipped through and prolly occurred with the resolver introduction). Second there is a high chance, that with omitting them in the resolver things might not update the same way for model instances vs. querysets anymore. My first guess is, that the resolver needs a proxy to source model mapping to still treat them equally. But without further tests, thats only a guess atm.

If you want to have a look at all these steps, feel free to do so. But note that the needed changes might be quite involving.
