### ISSUE TITLE
Computed fields of model inheriting Abstract model get polluted by fields from other model

### ISSUE THREAD

**Issue by mobiware** [netzkolchose/django-computedfields#41]
When 2 models inherit the same Abstract Model, there are situations where the computed fields of one model end up polluting those of the other model.
It is the case if the Abstract model defines its own computed fields.

I have implemented a repro test case and a fix, PR coming up soon

**Comment by mobiware** [comment]
Without the fix, tests would error out with the following stack:
```
Traceback (most recent call last):
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/venv/lib/python3.7/site-packages/django/db/models/options.py", line 565, in get_field
    return self.fields_map[field_name]
KeyError: 'concrete_target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/computedfields/graph.py", line 520, in resolve_dependencies
    rel = cls._meta.get_field(symbol)
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/venv/lib/python3.7/site-packages/django/db/models/options.py", line 567, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: ConcreteWithForeignKey2 has no field named 'concrete_target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/venv/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/computedfields/apps.py", line 16, in ready
    ComputedFieldsModelType._resolve_dependencies()
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/computedfields/models.py", line 114, in _resolve_dependencies
    mcs._graph = ComputedModelsGraph(mcs._computed_models)
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/computedfields/graph.py", line 401, in __init__
    self.resolved = self.resolve_dependencies(computed_models)
  File "/Users/romain/Documents/Projets/Darwin/code/django-computedfields/example/computedfields/graph.py", line 523, in resolve_dependencies
    rel = getattr(cls, symbol).rel
AttributeError: type object 'ConcreteWithForeignKey2' has no attribute 'concrete_target'
```

**Comment by mobiware** [comment]
`concrete_target` is a field of `ConcreteWithForeignKey`, not `ConcreteWithForeignKey2`. Both models share the same parent Abstract Model. This was due to how we'd build `cls._computed_fields`. The Abstract Model own `dict` was copied over by reference to subclasses so they'd all share the same `dict` that mixed all their own fields

**Comment by jerch** [comment]
@mobiware Thx for figuring out.

Could you test if you see a similar issue with the other PR #39, which tries to get rid of the meta class and `ComputedFieldsModel`? I really want to push it there soon, the metaclass is a nasty burden for more complex inheritance situations.

I know that Django does some magic around abstract models, and I am not sure how to tackle this in a more reliable way. Any suggestions from your side?

**Comment by mobiware** [comment]
@jerch I ported my test case over to the v2 branch and it passed so it seems like your new implementation correctly handles abstract inheritance from the get-go (haven't had a chance to play with multi-table inheritance yet)

**Comment by jerch** [comment]
@mobiware Thx for testing out. Yeah the new way of doing things is quite different and the transition is not fully done yet. I basically ignored complex model inheritance in the tests so far (thus expect other awkwardities with the old code), imho the best tests we have in this regard are those from you (thx to your testing of mixed abstract setups).
