### ISSUE TITLE
ModuleNotFoundError: No module named 'computedfields'

### ISSUE THREAD

**Issue by steveperx** [netzkolchose/django-computedfields#66]
I'm using Django 2.2.16 and Python 3.8.3. I installed django-computedfields using pipenv: 

```pipenv install django-computedfields```

I then added 'computedfields' to INSTALLED_APPS in my settings file:

```python
INSTALLED_APPS = [
    # django apps
    ...
    # third-party apps
    ...
    'computedfields',
    ...
```

However, when the project restarted, I got the following error:
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/steve/.pyenv/versions/3.8.1/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/steve/.pyenv/versions/3.8.1/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/steve/.local/share/virtualenvs/djTracker-npCy7e_g/lib/python3.8/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/steve/.local/share/virtualenvs/djTracker-npCy7e_g/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/steve/.local/share/virtualenvs/djTracker-npCy7e_g/lib/python3.8/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/Users/steve/.local/share/virtualenvs/djTracker-npCy7e_g/lib/python3.8/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/steve/.local/share/virtualenvs/djTracker-npCy7e_g/lib/python3.8/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/steve/.local/share/virtualenvs/djTracker-npCy7e_g/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/steve/.local/share/virtualenvs/djTracker-npCy7e_g/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/steve/.local/share/virtualenvs/djTracker-npCy7e_g/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/steve/.pyenv/versions/3.8.1/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'computedfields'
```

It seems the project is not loading django-computedfields. I've looked through the docs and searched here and on Google, but no one else seems to have this issue. The docs indicate Python 3.8 and Django 2.2 are supported. What am I missing?

**Comment by jerch** [comment]
@steveperx Thats weird, never seen this happen. Can you actually locate the module folder under your <env>/.../site-packages? There should be a `computedfields` folder, and `pip freeze` should show it up in the list.

**Comment by steveperx** [comment]
Yes, I was able to find it under site-packages. I got it working by copying the `computedfields` folder to my local project directory and importing it as if it were my own app using `computedfields.apps.ComputedfieldsConfig`.

Interestingly, running `pip freeze` does NOT show it in the list. Not sure why.

**Comment by jerch** [comment]
@steveperx Maybe thats an issue with `pipenv`? I never used that, could it be that it does not announce the installed package back to pip itself?

**Comment by steveperx** [comment]
@jerch Maybe... but I decided to remove and reinstall.  So, this time, I deleted the "local" copy of computedfields and pipenv uninstalled jsut to make sure it wasn't in `site-packages`.  The computedfields site package was removed and appropriately did not show up in a `pip freeze` command, and was not in the Pipfile. Then I pipenv installed django-computedfields again, and THIS time, the site package was installed, but running `pip freeze` shows `django-computedfields==0.1.3` has been installed.  Likewise, it shows up in the Pipfile. HOWEVER, I still get the same message when I `manage.py runserver`.

This is the weirdest thing.

**Comment by jerch** [comment]
@steveperx Eww, I dont know whats going on, this makes no sense to me at all. It seems that for some reason the env paths/interpreters got mixed up. But if thats the case django and any other django module should not run either (if you installed them the same way). Maybe try to set it up cleanly in a fresh path? The package does not do any weird install hack, it is just a plain source package distribution, thus there is no wheel package (Maybe thats an issue for pipenv?)

**Comment by steveperx** [comment]
I think this is an issue with my development environment and/or machine. I moved the project to another computer, and everything is working fine. I'm closing this as not related to the django-computedfields project.
